<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Expense extends Model
{
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($fuel){
            $relationsMethods = ['fuel'];
            foreach ($relationsMethods as $relationsMethod){
                if ($fuel->$relationsMethod()->count() > 0){
                    return false;
                }
            }
        });
    }

    public function fuel()
    {
        return $this->belongsTo(Fuel::class,'id','expense_id');
    }
}
