<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ServiceType extends Model
{
    protected $guarded = [];
protected static function boot()
{
    parent::boot(); // TODO: Change the autogenerated stub
    static::deleting(function ($service){
        $relationMethods = ['machines'];
        foreach ($relationMethods as $relationMethod){
            if ($service->$relationMethod()->count() > 0){
                return false;
            }
        }
    });
}

    public function track()
    {
        return $this->belongsTo(TrackBy::class,'track_by_id');
    }
    public function machines()
    {
        return $this->belongsToMany(Machine::class, 'machine_service_type');
    }
}
